modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="oresnstuff"
version="1.0.0"
displayName="oresnstuff"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="BrownBear85, UnhealthyPoro"
description='''
adds ores, n, stuff
'''

[[dependencies.oresnstuff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




